name: Version-Check

on: [push]

jobs:
  directory-check:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Print Working Directory
        run: pwd

      - name: List Directories
        run: ls

      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"