name: Version-Check

on: [push]

env:

  VULKAN_VERSION: 1.3.200

jobs:
  directory-check:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          persist-credentials: false
          fetch-depth: 0
      
      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"

      - name: Install pyyaml library
        run: pip install pyyaml
      
      - name: Run Vulkan Version Check
        run: python3 ./UpdateCheck.py

      - name: Commit files
        run: |
          git config --local user.name  ${{ github.actor }}
          git add ./.github
          git commit -m "Updating the Vulkan version for Github Actions."

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          force: true
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}

